CREATE USER 'REPLACE_USER_NEXTCLOUD'@'%' IDENTIFIED BY 'NEXT_PASS';
CREATE USER 'REPLACE_USER_WORDPRESS'@'%' IDENTIFIED BY 'WORDPRESS_PASS';
CREATE DATABASE IF NOT EXISTS nextclouddb;
CREATE DATABASE IF NOT EXISTS wordpressdb;
GRANT ALL ON nextclouddb.* TO 'REPLACE_USER_NEXTCLOUD'@'%';
GRANT ALL ON wordpress.* TO 'REPLACE_USER_WORDPRESS'@'%';
FLUSH PRIVILEGES;
